### ISSUE TITLE
Articles show is broken

### ISSUE THREAD

**Issue by tgaffer52** [Benja-Wainer/tellus#104]
It shows a 404. We need to implement modals fir the links in the map popup, sidebar, and profile page. Also, to use Chat-GPT topic generation, we need to ajax fetch the articles controller.

**Comment by christprix** [comment]
Not sure if we can get modals on the map popup because that would require every countries article on the entire map to be loaded up once we click on the map. I think doing an ajax request for each modal might work though. I can work on the side bar and profile page though. Lmk if you have some time to talk about how to implement the modal on the map.
